// Currency data interface
export interface CurrencyItem {
  DisplayCountry: string;
  CurrencyCode: string;
  DisplayCountry_CurrencyCode: string;
  DisplayCurrencySymbol: string;
  SymbolPosition: number; // 0: symbol before number, 1: symbol after number
  Country: string;
  CurrencySymbol: string;
}

// Full currency data from currency-final.csv
export const CURRENCY_DATA: CurrencyItem[] = [
  { DisplayCountry: "Afghanistan", CurrencyCode: "AFN", DisplayCountry_CurrencyCode: "Afghanistan (AFN)", DisplayCurrencySymbol: "؋", SymbolPosition: 0, Country: "Afghanistan", CurrencySymbol: "؋" },
  { DisplayCountry: "Albania", CurrencyCode: "ALL", DisplayCountry_CurrencyCode: "Albania (ALL)", DisplayCurrencySymbol: "Lek", SymbolPosition: 1, Country: "Albania", CurrencySymbol: "Lek" },
  { DisplayCountry: "Algeria", CurrencyCode: "DZD", DisplayCountry_CurrencyCode: "Algeria (DZD)", DisplayCurrencySymbol: "د.ج", SymbolPosition: 0, Country: "Algeria", CurrencySymbol: "د.ج" },
  { DisplayCountry: "American Samoa", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "American Samoa (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "American Samoa", CurrencySymbol: "$" },
  { DisplayCountry: "Andorra", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Andorra (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Andorra", CurrencySymbol: "€" },
  { DisplayCountry: "Angola", CurrencyCode: "AOA", DisplayCountry_CurrencyCode: "Angola (AOA)", DisplayCurrencySymbol: "Kz", SymbolPosition: 0, Country: "Angola", CurrencySymbol: "Kz" },
  { DisplayCountry: "Anguilla", CurrencyCode: "XCD", DisplayCountry_CurrencyCode: "Anguilla (XCD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Anguilla", CurrencySymbol: "$" },
  { DisplayCountry: "Antigua & Barbuda", CurrencyCode: "XCD", DisplayCountry_CurrencyCode: "Antigua & Barbuda (XCD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Antigua and Barbuda", CurrencySymbol: "$" },
  { DisplayCountry: "Argentina", CurrencyCode: "ARS", DisplayCountry_CurrencyCode: "Argentina (ARS)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Argentina", CurrencySymbol: "$" },
  { DisplayCountry: "Armenia", CurrencyCode: "AMD", DisplayCountry_CurrencyCode: "Armenia (AMD)", DisplayCurrencySymbol: "Դ", SymbolPosition: 1, Country: "Armenia", CurrencySymbol: "Դ" },
  { DisplayCountry: "Aruba", CurrencyCode: "AWG", DisplayCountry_CurrencyCode: "Aruba (AWG)", DisplayCurrencySymbol: "ƒ", SymbolPosition: 0, Country: "Aruba", CurrencySymbol: "ƒ" },
  { DisplayCountry: "Australia", CurrencyCode: "AUD", DisplayCountry_CurrencyCode: "Australia (AUD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Australia", CurrencySymbol: "$" },
  { DisplayCountry: "Austria", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Austria (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Austria", CurrencySymbol: "€" },
  { DisplayCountry: "Azerbaijan", CurrencyCode: "AZN", DisplayCountry_CurrencyCode: "Azerbaijan (AZN)", DisplayCurrencySymbol: "₼", SymbolPosition: 1, Country: "Azerbaijan", CurrencySymbol: "₼" },
  { DisplayCountry: "Bahamas", CurrencyCode: "BSD", DisplayCountry_CurrencyCode: "Bahamas (BSD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Bahamas", CurrencySymbol: "$" },
  { DisplayCountry: "Bahrain", CurrencyCode: "BHD", DisplayCountry_CurrencyCode: "Bahrain (BHD)", DisplayCurrencySymbol: "ب.د", SymbolPosition: 0, Country: "Bahrain", CurrencySymbol: "ب.د" },
  { DisplayCountry: "Bangladesh", CurrencyCode: "BDT", DisplayCountry_CurrencyCode: "Bangladesh (BDT)", DisplayCurrencySymbol: "৳", SymbolPosition: 0, Country: "Bangladesh", CurrencySymbol: "৳" },
  { DisplayCountry: "Barbados", CurrencyCode: "BBD", DisplayCountry_CurrencyCode: "Barbados (BBD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Barbados", CurrencySymbol: "$" },
  { DisplayCountry: "Belarus", CurrencyCode: "BYN", DisplayCountry_CurrencyCode: "Belarus (BYN)", DisplayCurrencySymbol: "p.", SymbolPosition: 1, Country: "Belarus", CurrencySymbol: "p." },
  { DisplayCountry: "Belgium", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Belgium (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Belgium", CurrencySymbol: "€" },
  { DisplayCountry: "Belize", CurrencyCode: "BZD", DisplayCountry_CurrencyCode: "Belize (BZD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Belize", CurrencySymbol: "$" },
  { DisplayCountry: "Benin", CurrencyCode: "XOF", DisplayCountry_CurrencyCode: "Benin (XOF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Benin", CurrencySymbol: "Franc" },
  { DisplayCountry: "Bermuda", CurrencyCode: "BMD", DisplayCountry_CurrencyCode: "Bermuda (BMD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Bermuda", CurrencySymbol: "$" },
  { DisplayCountry: "Bhutan", CurrencyCode: "BTN", DisplayCountry_CurrencyCode: "Bhutan (BTN)", DisplayCurrencySymbol: "Nu.", SymbolPosition: 0, Country: "Bhutan", CurrencySymbol: "Nu." },
  { DisplayCountry: "Bolivia", CurrencyCode: "BOB", DisplayCountry_CurrencyCode: "Bolivia (BOB)", DisplayCurrencySymbol: "Bs.", SymbolPosition: 0, Country: "Bolivia", CurrencySymbol: "Bs." },
//   { DisplayCountry: "Bolivia", CurrencyCode: "BOV", DisplayCountry_CurrencyCode: "Bolivia (BOV)", DisplayCurrencySymbol: "BOV", SymbolPosition: 1, Country: "Bolivia", CurrencySymbol: "Mvdol" },
  { DisplayCountry: "Bonaire", CurrencyCode: "BES", DisplayCountry_CurrencyCode: "Bonaire (BES)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Bonaire", CurrencySymbol: "$" },
  { DisplayCountry: "Bosnia & Herz.", CurrencyCode: "BAM", DisplayCountry_CurrencyCode: "Bosnia & Herz. (BAM)", DisplayCurrencySymbol: "КМ", SymbolPosition: 1, Country: "Bosnia and Herzegovina", CurrencySymbol: "КМ" },
  { DisplayCountry: "Botswana", CurrencyCode: "BWP", DisplayCountry_CurrencyCode: "Botswana (BWP)", DisplayCurrencySymbol: "P", SymbolPosition: 0, Country: "Botswana", CurrencySymbol: "P" },
  { DisplayCountry: "Bouvet Island", CurrencyCode: "NOK", DisplayCountry_CurrencyCode: "Bouvet Island (NOK)", DisplayCurrencySymbol: "kr", SymbolPosition: 1, Country: "Bouvet Island", CurrencySymbol: "kr" },
  { DisplayCountry: "Brazil", CurrencyCode: "BRL", DisplayCountry_CurrencyCode: "Brazil (BRL)", DisplayCurrencySymbol: "R$", SymbolPosition: 0, Country: "Brazil", CurrencySymbol: "R$" },
  { DisplayCountry: "British Indian Ocean T.", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "British Indian Ocean T. (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "British Indian Ocean Territory", CurrencySymbol: "$" },
  { DisplayCountry: "Brunei Darussalam", CurrencyCode: "BND", DisplayCountry_CurrencyCode: "Brunei Darussalam (BND)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Brunei Darussalam", CurrencySymbol: "$" },
  { DisplayCountry: "Bulgaria", CurrencyCode: "BGN", DisplayCountry_CurrencyCode: "Bulgaria (BGN)", DisplayCurrencySymbol: "лв", SymbolPosition: 1, Country: "Bulgaria", CurrencySymbol: "лв" },
  { DisplayCountry: "Burkina Faso", CurrencyCode: "XOF", DisplayCountry_CurrencyCode: "Burkina Faso (XOF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Burkina Faso", CurrencySymbol: "Franc" },
  { DisplayCountry: "Burundi", CurrencyCode: "BIF", DisplayCountry_CurrencyCode: "Burundi (BIF)", DisplayCurrencySymbol: "₣", SymbolPosition: 1, Country: "Burundi", CurrencySymbol: "₣" },
  { DisplayCountry: "Cape Verde", CurrencyCode: "CVE", DisplayCountry_CurrencyCode: "Cape Verde (CVE)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Cape Verde", CurrencySymbol: "$" },
  { DisplayCountry: "Cambodia", CurrencyCode: "KHR", DisplayCountry_CurrencyCode: "Cambodia (KHR)", DisplayCurrencySymbol: "៛", SymbolPosition: 0, Country: "Cambodia", CurrencySymbol: "៛" },
  { DisplayCountry: "Cameroon", CurrencyCode: "XAF", DisplayCountry_CurrencyCode: "Cameroon (XAF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Cameroon", CurrencySymbol: "CFA Franc BEAC" },
  { DisplayCountry: "Canada", CurrencyCode: "CAD", DisplayCountry_CurrencyCode: "Canada (CAD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Canada", CurrencySymbol: "$" },
  { DisplayCountry: "Cayman Islands", CurrencyCode: "KYD", DisplayCountry_CurrencyCode: "Cayman Islands (KYD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Cayman Islands", CurrencySymbol: "$" },
  { DisplayCountry: "Central African Rep.", CurrencyCode: "XAF", DisplayCountry_CurrencyCode: "Central African Rep. (XAF)", DisplayCurrencySymbol: "₣", SymbolPosition: 1, Country: "Central African Republic", CurrencySymbol: "₣" },
  { DisplayCountry: "Chad", CurrencyCode: "XAF", DisplayCountry_CurrencyCode: "Chad (XAF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Chad", CurrencySymbol: "CFA Franc BEAC" },
  { DisplayCountry: "Chile", CurrencyCode: "CLP", DisplayCountry_CurrencyCode: "Chile (CLP)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Chile", CurrencySymbol: "$" },
  { DisplayCountry: "China", CurrencyCode: "CNY", DisplayCountry_CurrencyCode: "China (CNY)", DisplayCurrencySymbol: "¥", SymbolPosition: 0, Country: "China", CurrencySymbol: "¥" },
  { DisplayCountry: "Christmas Island", CurrencyCode: "AUD", DisplayCountry_CurrencyCode: "Christmas Island (AUD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Christmas Island", CurrencySymbol: "$" },
  { DisplayCountry: "Cocos Islands", CurrencyCode: "AUD", DisplayCountry_CurrencyCode: "Cocos Islands (AUD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Cocos (Keeling) Islands", CurrencySymbol: "$" },
  { DisplayCountry: "Colombia", CurrencyCode: "COP", DisplayCountry_CurrencyCode: "Colombia (COP)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Colombia", CurrencySymbol: "$" },
  { DisplayCountry: "Comoros", CurrencyCode: "KMF", DisplayCountry_CurrencyCode: "Comoros (KMF)", DisplayCurrencySymbol: "FC", SymbolPosition: 1, Country: "Comoros", CurrencySymbol: "FC" },
  { DisplayCountry: "DR Congo", CurrencyCode: "CDF", DisplayCountry_CurrencyCode: "DR Congo (CDF)", DisplayCurrencySymbol: "₣", SymbolPosition: 1, Country: "Democratic Republic of the Congo", CurrencySymbol: "₣" },
  { DisplayCountry: "Cook Islands", CurrencyCode: "NZD", DisplayCountry_CurrencyCode: "Cook Islands (NZD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Cook Islands", CurrencySymbol: "$" },
  { DisplayCountry: "Costa Rica", CurrencyCode: "CRC", DisplayCountry_CurrencyCode: "Costa Rica (CRC)", DisplayCurrencySymbol: "₡", SymbolPosition: 0, Country: "Costa Rica", CurrencySymbol: "₡" },
  { DisplayCountry: "Croatia", CurrencyCode: "HRK", DisplayCountry_CurrencyCode: "Croatia (HRK)", DisplayCurrencySymbol: "Kn", SymbolPosition: 1, Country: "Croatia", CurrencySymbol: "Kn" },
  { DisplayCountry: "Cuba", CurrencyCode: "CUP", DisplayCountry_CurrencyCode: "Cuba (CUP)", DisplayCurrencySymbol: "₱", SymbolPosition: 0, Country: "Cuba", CurrencySymbol: "₱" },
  { DisplayCountry: "Curaçao", CurrencyCode: "ANG", DisplayCountry_CurrencyCode: "Curaçao (ANG)", DisplayCurrencySymbol: "ƒ", SymbolPosition: 0, Country: "Curaçao", CurrencySymbol: "ƒ" },
  { DisplayCountry: "Cyprus", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Cyprus (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Cyprus", CurrencySymbol: "€" },
  { DisplayCountry: "Czech Republic", CurrencyCode: "CZK", DisplayCountry_CurrencyCode: "Czech Republic (CZK)", DisplayCurrencySymbol: "Kč", SymbolPosition: 1, Country: "Czech Republic", CurrencySymbol: "Kč" },
  { DisplayCountry: "Ivory Coast", CurrencyCode: "XOF", DisplayCountry_CurrencyCode: "Ivory Coast (XOF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Ivory Coast", CurrencySymbol: "Franc" },
  { DisplayCountry: "Denmark", CurrencyCode: "DKK", DisplayCountry_CurrencyCode: "Denmark (DKK)", DisplayCurrencySymbol: "kr.", SymbolPosition: 1, Country: "Denmark", CurrencySymbol: "kr." },
  { DisplayCountry: "Djibouti", CurrencyCode: "DJF", DisplayCountry_CurrencyCode: "Djibouti (DJF)", DisplayCurrencySymbol: "₣", SymbolPosition: 1, Country: "Djibouti", CurrencySymbol: "₣" },
  { DisplayCountry: "Dominica", CurrencyCode: "XCD", DisplayCountry_CurrencyCode: "Dominica (XCD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Dominica", CurrencySymbol: "$" },
  { DisplayCountry: "Dominican Republic", CurrencyCode: "DOP", DisplayCountry_CurrencyCode: "Dominican Republic (DOP)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Dominican Republic", CurrencySymbol: "$" },
  { DisplayCountry: "Ecuador", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "Ecuador (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Ecuador", CurrencySymbol: "$" },
  { DisplayCountry: "Egypt", CurrencyCode: "EGP", DisplayCountry_CurrencyCode: "Egypt (EGP)", DisplayCurrencySymbol: "£", SymbolPosition: 0, Country: "Egypt", CurrencySymbol: "£" },
  { DisplayCountry: "El Salvador", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "El Salvador (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "El Salvador", CurrencySymbol: "$" },
  { DisplayCountry: "Equatorial Guinea", CurrencyCode: "XAF", DisplayCountry_CurrencyCode: "Equatorial Guinea (XAF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Equatorial Guinea", CurrencySymbol: "FCFA" },
  { DisplayCountry: "Eritrea", CurrencyCode: "ERN", DisplayCountry_CurrencyCode: "Eritrea (ERN)", DisplayCurrencySymbol: "Nfk", SymbolPosition: 0, Country: "Eritrea", CurrencySymbol: "Nfk" },
  { DisplayCountry: "Estonia", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Estonia (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Estonia", CurrencySymbol: "€" },
  { DisplayCountry: "Ethiopia", CurrencyCode: "ETB", DisplayCountry_CurrencyCode: "Ethiopia (ETB)", DisplayCurrencySymbol: "Br", SymbolPosition: 0, Country: "Ethiopia", CurrencySymbol: "Br" },
  { DisplayCountry: "Falkland Islands", CurrencyCode: "FKP", DisplayCountry_CurrencyCode: "Falkland Islands (FKP)", DisplayCurrencySymbol: "£", SymbolPosition: 0, Country: "Falkland Islands", CurrencySymbol: "£" },
  { DisplayCountry: "Faroe Islands", CurrencyCode: "DKK", DisplayCountry_CurrencyCode: "Faroe Islands (DKK)", DisplayCurrencySymbol: "kr.", SymbolPosition: 1, Country: "Faroe Islands", CurrencySymbol: "kr." },
  { DisplayCountry: "Fiji", CurrencyCode: "FJD", DisplayCountry_CurrencyCode: "Fiji (FJD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Fiji", CurrencySymbol: "$" },
  { DisplayCountry: "Finland", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Finland (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Finland", CurrencySymbol: "€" },
  { DisplayCountry: "France", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "France (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "France", CurrencySymbol: "€" },
  { DisplayCountry: "French Guiana", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "French Guiana (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "French Guiana", CurrencySymbol: "€" },
  { DisplayCountry: "French Polynesia", CurrencyCode: "XPF", DisplayCountry_CurrencyCode: "French Polynesia (XPF)", DisplayCurrencySymbol: "₣", SymbolPosition: 1, Country: "French Polynesia", CurrencySymbol: "₣" },
  { DisplayCountry: "French Southern Territories", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "French Southern Territories (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "French Southern Territories", CurrencySymbol: "€" },
  { DisplayCountry: "Gabon", CurrencyCode: "XAF", DisplayCountry_CurrencyCode: "Gabon (XAF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Gabon", CurrencySymbol: "FCFA" },
  { DisplayCountry: "Gambia", CurrencyCode: "GMD", DisplayCountry_CurrencyCode: "Gambia (GMD)", DisplayCurrencySymbol: "D", SymbolPosition: 0, Country: "Gambia", CurrencySymbol: "D" },
  { DisplayCountry: "Georgia", CurrencyCode: "GEL", DisplayCountry_CurrencyCode: "Georgia (GEL)", DisplayCurrencySymbol: "ლ", SymbolPosition: 1, Country: "Georgia", CurrencySymbol: "ლ" },
  { DisplayCountry: "Germany", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Germany (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Germany", CurrencySymbol: "€" },
  { DisplayCountry: "Ghana", CurrencyCode: "GHS", DisplayCountry_CurrencyCode: "Ghana (GHS)", DisplayCurrencySymbol: "₵", SymbolPosition: 0, Country: "Ghana", CurrencySymbol: "₵" },
  { DisplayCountry: "Gibraltar", CurrencyCode: "GIP", DisplayCountry_CurrencyCode: "Gibraltar (GIP)", DisplayCurrencySymbol: "£", SymbolPosition: 0, Country: "Gibraltar", CurrencySymbol: "£" },
  { DisplayCountry: "Greece", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Greece (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Greece", CurrencySymbol: "€" },
  { DisplayCountry: "Greenland", CurrencyCode: "DKK", DisplayCountry_CurrencyCode: "Greenland (DKK)", DisplayCurrencySymbol: "kr.", SymbolPosition: 1, Country: "Greenland", CurrencySymbol: "kr." },
  { DisplayCountry: "Grenada", CurrencyCode: "XCD", DisplayCountry_CurrencyCode: "Grenada (XCD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Grenada", CurrencySymbol: "$" },
  { DisplayCountry: "Guadeloupe", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Guadeloupe (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Guadeloupe", CurrencySymbol: "€" },
  { DisplayCountry: "Guam", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "Guam (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Guam", CurrencySymbol: "$" },
  { DisplayCountry: "Guatemala", CurrencyCode: "GTQ", DisplayCountry_CurrencyCode: "Guatemala (GTQ)", DisplayCurrencySymbol: "Q", SymbolPosition: 0, Country: "Guatemala", CurrencySymbol: "Q" },
  { DisplayCountry: "Guernsey", CurrencyCode: "GBP", DisplayCountry_CurrencyCode: "Guernsey (GBP)", DisplayCurrencySymbol: "£", SymbolPosition: 0, Country: "Guernsey", CurrencySymbol: "£" },
  { DisplayCountry: "Guinea", CurrencyCode: "GNF", DisplayCountry_CurrencyCode: "Guinea (GNF)", DisplayCurrencySymbol: "₣", SymbolPosition: 1, Country: "Guinea", CurrencySymbol: "₣" },
  { DisplayCountry: "Guinea-Bissau", CurrencyCode: "XOF", DisplayCountry_CurrencyCode: "Guinea-Bissau (XOF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Guinea-Bissau", CurrencySymbol: "Franc" },
  { DisplayCountry: "Guyana", CurrencyCode: "GYD", DisplayCountry_CurrencyCode: "Guyana (GYD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Guyana", CurrencySymbol: "$" },
  { DisplayCountry: "Haiti", CurrencyCode: "HTG", DisplayCountry_CurrencyCode: "Haiti (HTG)", DisplayCurrencySymbol: "G", SymbolPosition: 0, Country: "Haiti", CurrencySymbol: "G" },
//   { DisplayCountry: "Haiti", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "Haiti (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Haiti", CurrencySymbol: "$" },
  { DisplayCountry: "Heard & McDonald Is.", CurrencyCode: "AUD", DisplayCountry_CurrencyCode: "Heard & McDonald Is. (AUD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Heard and McDonald Islands", CurrencySymbol: "$" },
  { DisplayCountry: "Holy See", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Holy See (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Holy See", CurrencySymbol: "€" },
  { DisplayCountry: "Honduras", CurrencyCode: "HNL", DisplayCountry_CurrencyCode: "Honduras (HNL)", DisplayCurrencySymbol: "L", SymbolPosition: 0, Country: "Honduras", CurrencySymbol: "L" },
  { DisplayCountry: "Hong Kong", CurrencyCode: "HKD", DisplayCountry_CurrencyCode: "Hong Kong (HKD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Hong Kong", CurrencySymbol: "$" },
  { DisplayCountry: "Hungary", CurrencyCode: "HUF", DisplayCountry_CurrencyCode: "Hungary (HUF)", DisplayCurrencySymbol: "Ft", SymbolPosition: 1, Country: "Hungary", CurrencySymbol: "Ft" },
  { DisplayCountry: "Iceland", CurrencyCode: "ISK", DisplayCountry_CurrencyCode: "Iceland (ISK)", DisplayCurrencySymbol: "Kr", SymbolPosition: 1, Country: "Iceland", CurrencySymbol: "Kr" },
  { DisplayCountry: "India", CurrencyCode: "INR", DisplayCountry_CurrencyCode: "India (INR)", DisplayCurrencySymbol: "₹", SymbolPosition: 0, Country: "India", CurrencySymbol: "₹" },
  { DisplayCountry: "Indonesia", CurrencyCode: "IDR", DisplayCountry_CurrencyCode: "Indonesia (IDR)", DisplayCurrencySymbol: "Rp", SymbolPosition: 0, Country: "Indonesia", CurrencySymbol: "Rp" },
  { DisplayCountry: "Iran", CurrencyCode: "IRR", DisplayCountry_CurrencyCode: "Iran (IRR)", DisplayCurrencySymbol: "﷼", SymbolPosition: 0, Country: "Iran", CurrencySymbol: "﷼" },
  { DisplayCountry: "Iraq", CurrencyCode: "IQD", DisplayCountry_CurrencyCode: "Iraq (IQD)", DisplayCurrencySymbol: "ع.د", SymbolPosition: 0, Country: "Iraq", CurrencySymbol: "ع.د" },
  { DisplayCountry: "Ireland", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Ireland (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 0, Country: "Ireland", CurrencySymbol: "€" },
  { DisplayCountry: "Isle of Man", CurrencyCode: "GBP", DisplayCountry_CurrencyCode: "Isle of Man (GBP)", DisplayCurrencySymbol: "£", SymbolPosition: 0, Country: "Isle of Man", CurrencySymbol: "£" },
  { DisplayCountry: "Israel", CurrencyCode: "ILS", DisplayCountry_CurrencyCode: "Israel (ILS)", DisplayCurrencySymbol: "₪", SymbolPosition: 0, Country: "Israel", CurrencySymbol: "₪" },
  { DisplayCountry: "Italy", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Italy (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Italy", CurrencySymbol: "€" },
  { DisplayCountry: "Jamaica", CurrencyCode: "JMD", DisplayCountry_CurrencyCode: "Jamaica (JMD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Jamaica", CurrencySymbol: "$" },
  { DisplayCountry: "Japan", CurrencyCode: "JPY", DisplayCountry_CurrencyCode: "Japan (JPY)", DisplayCurrencySymbol: "¥", SymbolPosition: 0, Country: "Japan", CurrencySymbol: "¥" },
  { DisplayCountry: "Jersey", CurrencyCode: "GBP", DisplayCountry_CurrencyCode: "Jersey (GBP)", DisplayCurrencySymbol: "£", SymbolPosition: 0, Country: "Jersey", CurrencySymbol: "£" },
  { DisplayCountry: "Jordan", CurrencyCode: "JOD", DisplayCountry_CurrencyCode: "Jordan (JOD)", DisplayCurrencySymbol: "د.ا", SymbolPosition: 0, Country: "Jordan", CurrencySymbol: "د.ا" },
  { DisplayCountry: "Kazakhstan", CurrencyCode: "KZT", DisplayCountry_CurrencyCode: "Kazakhstan (KZT)", DisplayCurrencySymbol: "〒", SymbolPosition: 1, Country: "Kazakhstan", CurrencySymbol: "〒" },
  { DisplayCountry: "Kenya", CurrencyCode: "KES", DisplayCountry_CurrencyCode: "Kenya (KES)", DisplayCurrencySymbol: "Sh", SymbolPosition: 0, Country: "Kenya", CurrencySymbol: "Sh" },
  { DisplayCountry: "Kiribati", CurrencyCode: "AUD", DisplayCountry_CurrencyCode: "Kiribati (AUD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Kiribati", CurrencySymbol: "$" },
  { DisplayCountry: "North Korea", CurrencyCode: "KPW", DisplayCountry_CurrencyCode: "North Korea (KPW)", DisplayCurrencySymbol: "₩", SymbolPosition: 1, Country: "North Korea", CurrencySymbol: "₩" },
  { DisplayCountry: "South Korea", CurrencyCode: "KRW", DisplayCountry_CurrencyCode: "South Korea (KRW)", DisplayCurrencySymbol: "₩", SymbolPosition: 1, Country: "South Korea", CurrencySymbol: "₩" },
  { DisplayCountry: "Kuwait", CurrencyCode: "KWD", DisplayCountry_CurrencyCode: "Kuwait (KWD)", DisplayCurrencySymbol: "د.ك", SymbolPosition: 0, Country: "Kuwait", CurrencySymbol: "د.ك" },
  { DisplayCountry: "Kyrgyzstan", CurrencyCode: "KGS", DisplayCountry_CurrencyCode: "Kyrgyzstan (KGS)", DisplayCurrencySymbol: "лв", SymbolPosition: 1, Country: "Kyrgyzstan", CurrencySymbol: "лв" },
  { DisplayCountry: "Laos", CurrencyCode: "LAK", DisplayCountry_CurrencyCode: "Laos (LAK)", DisplayCurrencySymbol: "₭", SymbolPosition: 0, Country: "Laos", CurrencySymbol: "₭" },
  { DisplayCountry: "Latvia", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Latvia (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Latvia", CurrencySymbol: "€" },
  { DisplayCountry: "Lebanon", CurrencyCode: "LBP", DisplayCountry_CurrencyCode: "Lebanon (LBP)", DisplayCurrencySymbol: "ل.ل", SymbolPosition: 0, Country: "Lebanon", CurrencySymbol: "ل.ل" },
  { DisplayCountry: "Lesotho", CurrencyCode: "LSL", DisplayCountry_CurrencyCode: "Lesotho (LSL)", DisplayCurrencySymbol: "L", SymbolPosition: 0, Country: "Lesotho", CurrencySymbol: "L" },
//   { DisplayCountry: "Lesotho", CurrencyCode: "ZAR", DisplayCountry_CurrencyCode: "Lesotho (ZAR)", DisplayCurrencySymbol: "R", SymbolPosition: 0, Country: "Lesotho", CurrencySymbol: "R" },
  { DisplayCountry: "Liberia", CurrencyCode: "LRD", DisplayCountry_CurrencyCode: "Liberia (LRD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Liberia", CurrencySymbol: "$" },
  { DisplayCountry: "Libya", CurrencyCode: "LYD", DisplayCountry_CurrencyCode: "Libya (LYD)", DisplayCurrencySymbol: "ل.د", SymbolPosition: 0, Country: "Libya", CurrencySymbol: "ل.د" },
  { DisplayCountry: "Liechtenstein", CurrencyCode: "CHF", DisplayCountry_CurrencyCode: "Liechtenstein (CHF)", DisplayCurrencySymbol: "₣", SymbolPosition: 0, Country: "Liechtenstein", CurrencySymbol: "₣" },
  { DisplayCountry: "Lithuania", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Lithuania (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Lithuania", CurrencySymbol: "€" },
  { DisplayCountry: "Luxembourg", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Luxembourg (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Luxembourg", CurrencySymbol: "€" },
  { DisplayCountry: "Macao", CurrencyCode: "MOP", DisplayCountry_CurrencyCode: "Macao (MOP)", DisplayCurrencySymbol: "P", SymbolPosition: 0, Country: "Macao", CurrencySymbol: "P" },
  { DisplayCountry: "Madagascar", CurrencyCode: "MGA", DisplayCountry_CurrencyCode: "Madagascar (MGA)", DisplayCurrencySymbol: "MK", SymbolPosition: 1, Country: "Madagascar", CurrencySymbol: "MK" },
  { DisplayCountry: "Malawi", CurrencyCode: "MWK", DisplayCountry_CurrencyCode: "Malawi (MWK)", DisplayCurrencySymbol: "MK", SymbolPosition: 0, Country: "Malawi", CurrencySymbol: "MK" },
  { DisplayCountry: "Malaysia", CurrencyCode: "MYR", DisplayCountry_CurrencyCode: "Malaysia (MYR)", DisplayCurrencySymbol: "RM", SymbolPosition: 0, Country: "Malaysia", CurrencySymbol: "RM" },
  { DisplayCountry: "Maldives", CurrencyCode: "MVR", DisplayCountry_CurrencyCode: "Maldives (MVR)", DisplayCurrencySymbol: "ރ", SymbolPosition: 0, Country: "Maldives", CurrencySymbol: "ރ" },
  { DisplayCountry: "Mali", CurrencyCode: "XOF", DisplayCountry_CurrencyCode: "Mali (XOF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Mali", CurrencySymbol: "Franc" },
  { DisplayCountry: "Malta", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Malta (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Malta", CurrencySymbol: "€" },
  { DisplayCountry: "Marshall Islands", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "Marshall Islands (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Marshall Islands", CurrencySymbol: "$" },
  { DisplayCountry: "Martinique", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Martinique (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Martinique", CurrencySymbol: "€" },
  { DisplayCountry: "Mauritania", CurrencyCode: "MRU", DisplayCountry_CurrencyCode: "Mauritania (MRU)", DisplayCurrencySymbol: "UM", SymbolPosition: 1, Country: "Mauritania", CurrencySymbol: "UM" },
  { DisplayCountry: "Mauritius", CurrencyCode: "MUR", DisplayCountry_CurrencyCode: "Mauritius (MUR)", DisplayCurrencySymbol: "₨", SymbolPosition: 0, Country: "Mauritius", CurrencySymbol: "₨" },
  { DisplayCountry: "Mayotte", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Mayotte (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Mayotte", CurrencySymbol: "€" },
  { DisplayCountry: "Mexico", CurrencyCode: "MXN", DisplayCountry_CurrencyCode: "Mexico (MXN)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Mexico", CurrencySymbol: "$" },
//   { DisplayCountry: "Mexico", CurrencyCode: "MXV", DisplayCountry_CurrencyCode: "Mexico (MXV)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Mexico", CurrencySymbol: "$" },
  { DisplayCountry: "Micronesia", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "Micronesia (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Micronesia", CurrencySymbol: "$" },
  { DisplayCountry: "Moldova", CurrencyCode: "MDL", DisplayCountry_CurrencyCode: "Moldova (MDL)", DisplayCurrencySymbol: "L", SymbolPosition: 1, Country: "Moldova", CurrencySymbol: "L" },
  { DisplayCountry: "Monaco", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Monaco (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Monaco", CurrencySymbol: "€" },
  { DisplayCountry: "Mongolia", CurrencyCode: "MNT", DisplayCountry_CurrencyCode: "Mongolia (MNT)", DisplayCurrencySymbol: "₮", SymbolPosition: 1, Country: "Mongolia", CurrencySymbol: "₮" },
  { DisplayCountry: "Montenegro", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Montenegro (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Montenegro", CurrencySymbol: "€" },
  { DisplayCountry: "Montserrat", CurrencyCode: "XCD", DisplayCountry_CurrencyCode: "Montserrat (XCD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Montserrat", CurrencySymbol: "$" },
  { DisplayCountry: "Morocco", CurrencyCode: "MAD", DisplayCountry_CurrencyCode: "Morocco (MAD)", DisplayCurrencySymbol: "د.م.", SymbolPosition: 0, Country: "Morocco", CurrencySymbol: "د.م." },
  { DisplayCountry: "Mozambique", CurrencyCode: "MZN", DisplayCountry_CurrencyCode: "Mozambique (MZN)", DisplayCurrencySymbol: "MTn", SymbolPosition: 0, Country: "Mozambique", CurrencySymbol: "MTn" },
  { DisplayCountry: "Myanmar", CurrencyCode: "MMK", DisplayCountry_CurrencyCode: "Myanmar (MMK)", DisplayCurrencySymbol: "K", SymbolPosition: 0, Country: "Myanmar", CurrencySymbol: "K" },
  { DisplayCountry: "Namibia", CurrencyCode: "NAD", DisplayCountry_CurrencyCode: "Namibia (NAD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Namibia", CurrencySymbol: "$" },
//   { DisplayCountry: "Namibia", CurrencyCode: "ZAR", DisplayCountry_CurrencyCode: "Namibia (ZAR)", DisplayCurrencySymbol: "R", SymbolPosition: 0, Country: "Namibia", CurrencySymbol: "R" },
  { DisplayCountry: "Nauru", CurrencyCode: "AUD", DisplayCountry_CurrencyCode: "Nauru (AUD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Nauru", CurrencySymbol: "$" },
  { DisplayCountry: "Nepal", CurrencyCode: "NPR", DisplayCountry_CurrencyCode: "Nepal (NPR)", DisplayCurrencySymbol: "₨", SymbolPosition: 0, Country: "Nepal", CurrencySymbol: "₨" },
  { DisplayCountry: "Netherlands", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Netherlands (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Netherlands", CurrencySymbol: "€" },
  { DisplayCountry: "New Caledonia", CurrencyCode: "XPF", DisplayCountry_CurrencyCode: "New Caledonia (XPF)", DisplayCurrencySymbol: "₣", SymbolPosition: 1, Country: "New Caledonia", CurrencySymbol: "₣" },
  { DisplayCountry: "New Zealand", CurrencyCode: "NZD", DisplayCountry_CurrencyCode: "New Zealand (NZD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "New Zealand", CurrencySymbol: "$" },
  { DisplayCountry: "Nicaragua", CurrencyCode: "NIO", DisplayCountry_CurrencyCode: "Nicaragua (NIO)", DisplayCurrencySymbol: "C$", SymbolPosition: 0, Country: "Nicaragua", CurrencySymbol: "C$" },
  { DisplayCountry: "Niger", CurrencyCode: "XOF", DisplayCountry_CurrencyCode: "Niger (XOF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Niger", CurrencySymbol: "Franc" },
  { DisplayCountry: "Nigeria", CurrencyCode: "NGN", DisplayCountry_CurrencyCode: "Nigeria (NGN)", DisplayCurrencySymbol: "₦", SymbolPosition: 0, Country: "Nigeria", CurrencySymbol: "₦" },
  { DisplayCountry: "Niue", CurrencyCode: "NZD", DisplayCountry_CurrencyCode: "Niue (NZD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Niue", CurrencySymbol: "$" },
  { DisplayCountry: "Norfolk Island", CurrencyCode: "AUD", DisplayCountry_CurrencyCode: "Norfolk Island (AUD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Norfolk Island", CurrencySymbol: "$" },
  { DisplayCountry: "Northern Mariana Islands", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "Northern Mariana Islands (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Northern Mariana Islands", CurrencySymbol: "$" },
  { DisplayCountry: "Norway", CurrencyCode: "NOK", DisplayCountry_CurrencyCode: "Norway (NOK)", DisplayCurrencySymbol: "kr", SymbolPosition: 1, Country: "Norway", CurrencySymbol: "kr" },
  { DisplayCountry: "Oman", CurrencyCode: "OMR", DisplayCountry_CurrencyCode: "Oman (OMR)", DisplayCurrencySymbol: "﷼", SymbolPosition: 0, Country: "Oman", CurrencySymbol: "﷼" },
  { DisplayCountry: "Pakistan", CurrencyCode: "PKR", DisplayCountry_CurrencyCode: "Pakistan (PKR)", DisplayCurrencySymbol: "₨", SymbolPosition: 0, Country: "Pakistan", CurrencySymbol: "₨" },
  { DisplayCountry: "Palau", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "Palau (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Palau", CurrencySymbol: "$" },
//   { DisplayCountry: "Panama", CurrencyCode: "PAB", DisplayCountry_CurrencyCode: "Panama (PAB)", DisplayCurrencySymbol: "B/.", SymbolPosition: 0, Country: "Panama", CurrencySymbol: "B/." },
  { DisplayCountry: "Panama", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "Panama (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Panama", CurrencySymbol: "$" },
  { DisplayCountry: "Papua New Guinea", CurrencyCode: "PGK", DisplayCountry_CurrencyCode: "Papua New Guinea (PGK)", DisplayCurrencySymbol: "K", SymbolPosition: 0, Country: "Papua New Guinea", CurrencySymbol: "K" },
  { DisplayCountry: "Paraguay", CurrencyCode: "PYG", DisplayCountry_CurrencyCode: "Paraguay (PYG)", DisplayCurrencySymbol: "₲", SymbolPosition: 0, Country: "Paraguay", CurrencySymbol: "₲" },
  { DisplayCountry: "Peru", CurrencyCode: "PEN", DisplayCountry_CurrencyCode: "Peru (PEN)", DisplayCurrencySymbol: "S/.", SymbolPosition: 0, Country: "Peru", CurrencySymbol: "S/." },
  { DisplayCountry: "Philippines", CurrencyCode: "PHP", DisplayCountry_CurrencyCode: "Philippines (PHP)", DisplayCurrencySymbol: "₱", SymbolPosition: 0, Country: "Philippines", CurrencySymbol: "₱" },
  { DisplayCountry: "Pitcairn Islands", CurrencyCode: "NZD", DisplayCountry_CurrencyCode: "Pitcairn Islands (NZD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Pitcairn Islands", CurrencySymbol: "$" },
  { DisplayCountry: "Poland", CurrencyCode: "PLN", DisplayCountry_CurrencyCode: "Poland (PLN)", DisplayCurrencySymbol: "zł", SymbolPosition: 1, Country: "Poland", CurrencySymbol: "zł" },
  { DisplayCountry: "Portugal", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Portugal (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Portugal", CurrencySymbol: "€" },
  { DisplayCountry: "Puerto Rico", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "Puerto Rico (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Puerto Rico", CurrencySymbol: "$" },
  { DisplayCountry: "Qatar", CurrencyCode: "QAR", DisplayCountry_CurrencyCode: "Qatar (QAR)", DisplayCurrencySymbol: "ر.ق", SymbolPosition: 0, Country: "Qatar", CurrencySymbol: "ر.ق" },
  { DisplayCountry: "North Macedonia", CurrencyCode: "MKD", DisplayCountry_CurrencyCode: "North Macedonia (MKD)", DisplayCurrencySymbol: "ден", SymbolPosition: 1, Country: "North Macedonia", CurrencySymbol: "ден" },
  { DisplayCountry: "Romania", CurrencyCode: "RON", DisplayCountry_CurrencyCode: "Romania (RON)", DisplayCurrencySymbol: "L", SymbolPosition: 1, Country: "Romania", CurrencySymbol: "L" },
  { DisplayCountry: "Russia", CurrencyCode: "RUB", DisplayCountry_CurrencyCode: "Russia (RUB)", DisplayCurrencySymbol: "₽", SymbolPosition: 1, Country: "Russia", CurrencySymbol: "₽" },
  { DisplayCountry: "Rwanda", CurrencyCode: "RWF", DisplayCountry_CurrencyCode: "Rwanda (RWF)", DisplayCurrencySymbol: "₣", SymbolPosition: 1, Country: "Rwanda", CurrencySymbol: "₣" },
  { DisplayCountry: "Réunion", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Réunion (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Réunion", CurrencySymbol: "€" },
  { DisplayCountry: "St Barthélemy", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "St Barthélemy (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Saint Barthélemy", CurrencySymbol: "€" },
  { DisplayCountry: "Saint Helena", CurrencyCode: "SHP", DisplayCountry_CurrencyCode: "Saint Helena (SHP)", DisplayCurrencySymbol: "£", SymbolPosition: 0, Country: "Saint Helena", CurrencySymbol: "£" },
  { DisplayCountry: "Saint Kitts and Nevis", CurrencyCode: "XCD", DisplayCountry_CurrencyCode: "Saint Kitts and Nevis (XCD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Saint Kitts and Nevis", CurrencySymbol: "$" },
  { DisplayCountry: "Saint Lucia", CurrencyCode: "XCD", DisplayCountry_CurrencyCode: "Saint Lucia (XCD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Saint Lucia", CurrencySymbol: "$" },
  { DisplayCountry: "Saint Martin", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Saint Martin (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Saint Martin", CurrencySymbol: "€" },
  { DisplayCountry: "St Pierre & Miquelon", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "St Pierre & Miquelon (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Saint Pierre and Miquelon", CurrencySymbol: "€" },
  { DisplayCountry: "St Vincent & Grenadines", CurrencyCode: "XCD", DisplayCountry_CurrencyCode: "St Vincent & Grenadines (XCD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Saint Vincent and the Grenadines", CurrencySymbol: "$" },
  { DisplayCountry: "Samoa", CurrencyCode: "WST", DisplayCountry_CurrencyCode: "Samoa (WST)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Samoa", CurrencySymbol: "$" },
  { DisplayCountry: "San Marino", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "San Marino (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "San Marino", CurrencySymbol: "€" },
  { DisplayCountry: "Sao Tome and Principe", CurrencyCode: "STN", DisplayCountry_CurrencyCode: "Sao Tome and Principe (STN)", DisplayCurrencySymbol: "Db", SymbolPosition: 0, Country: "Sao Tome and Principe", CurrencySymbol: "Db" },
  { DisplayCountry: "Saudi Arabia", CurrencyCode: "SAR", DisplayCountry_CurrencyCode: "Saudi Arabia (SAR)", DisplayCurrencySymbol: "ر.س", SymbolPosition: 0, Country: "Saudi Arabia", CurrencySymbol: "ر.س" },
  { DisplayCountry: "Senegal", CurrencyCode: "XOF", DisplayCountry_CurrencyCode: "Senegal (XOF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Senegal", CurrencySymbol: "Franc" },
  { DisplayCountry: "Serbia", CurrencyCode: "RSD", DisplayCountry_CurrencyCode: "Serbia (RSD)", DisplayCurrencySymbol: "din", SymbolPosition: 1, Country: "Serbia", CurrencySymbol: "din" },
  { DisplayCountry: "Seychelles", CurrencyCode: "SCR", DisplayCountry_CurrencyCode: "Seychelles (SCR)", DisplayCurrencySymbol: "Rs", SymbolPosition: 0, Country: "Seychelles", CurrencySymbol: "Rs" },
  { DisplayCountry: "Sierra Leone", CurrencyCode: "SLL", DisplayCountry_CurrencyCode: "Sierra Leone (SLL)", DisplayCurrencySymbol: "Le", SymbolPosition: 0, Country: "Sierra Leone", CurrencySymbol: "Le" },
  { DisplayCountry: "Singapore", CurrencyCode: "SGD", DisplayCountry_CurrencyCode: "Singapore (SGD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Singapore", CurrencySymbol: "$" },
  { DisplayCountry: "Sint Maarten", CurrencyCode: "ANG", DisplayCountry_CurrencyCode: "Sint Maarten (ANG)", DisplayCurrencySymbol: "ƒ", SymbolPosition: 0, Country: "Sint Maarten", CurrencySymbol: "ƒ" },
  { DisplayCountry: "Slovakia", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Slovakia (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Slovakia", CurrencySymbol: "€" },
  { DisplayCountry: "Slovenia", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Slovenia (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Slovenia", CurrencySymbol: "€" },
  { DisplayCountry: "Solomon Islands", CurrencyCode: "SBD", DisplayCountry_CurrencyCode: "Solomon Islands (SBD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Solomon Islands", CurrencySymbol: "$" },
  { DisplayCountry: "Somalia", CurrencyCode: "SOS", DisplayCountry_CurrencyCode: "Somalia (SOS)", DisplayCurrencySymbol: "Sh", SymbolPosition: 0, Country: "Somalia", CurrencySymbol: "Sh" },
  { DisplayCountry: "South Africa", CurrencyCode: "ZAR", DisplayCountry_CurrencyCode: "South Africa (ZAR)", DisplayCurrencySymbol: "R", SymbolPosition: 0, Country: "South Africa", CurrencySymbol: "R" },
  { DisplayCountry: "South Sudan", CurrencyCode: "SSP", DisplayCountry_CurrencyCode: "South Sudan (SSP)", DisplayCurrencySymbol: "SS£", SymbolPosition: 0, Country: "South Sudan", CurrencySymbol: "SS£" },
  { DisplayCountry: "Spain", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Spain (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Spain", CurrencySymbol: "€" },
  { DisplayCountry: "Sri Lanka", CurrencyCode: "LKR", DisplayCountry_CurrencyCode: "Sri Lanka (LKR)", DisplayCurrencySymbol: "Rs", SymbolPosition: 0, Country: "Sri Lanka", CurrencySymbol: "Rs" },
  { DisplayCountry: "Sudan", CurrencyCode: "SDG", DisplayCountry_CurrencyCode: "Sudan (SDG)", DisplayCurrencySymbol: "£", SymbolPosition: 0, Country: "Sudan", CurrencySymbol: "£" },
  { DisplayCountry: "Suriname", CurrencyCode: "SRD", DisplayCountry_CurrencyCode: "Suriname (SRD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Suriname", CurrencySymbol: "$" },
  { DisplayCountry: "Svalbard", CurrencyCode: "NOK", DisplayCountry_CurrencyCode: "Svalbard (NOK)", DisplayCurrencySymbol: "kr", SymbolPosition: 1, Country: "Svalbard and Jan Mayen", CurrencySymbol: "kr" },
  { DisplayCountry: "Swaziland (Eswatini)", CurrencyCode: "SZL", DisplayCountry_CurrencyCode: "Swaziland (Eswatini) (SZL)", DisplayCurrencySymbol: "L", SymbolPosition: 0, Country: "Swaziland (Eswatini)", CurrencySymbol: "L" },
  { DisplayCountry: "Sweden", CurrencyCode: "SEK", DisplayCountry_CurrencyCode: "Sweden (SEK)", DisplayCurrencySymbol: "kr", SymbolPosition: 1, Country: "Sweden", CurrencySymbol: "kr" },
  { DisplayCountry: "Switzerland", CurrencyCode: "CHF", DisplayCountry_CurrencyCode: "Switzerland (CHF)", DisplayCurrencySymbol: "₣", SymbolPosition: 0, Country: "Switzerland", CurrencySymbol: "₣" },
  { DisplayCountry: "Syria", CurrencyCode: "SYP", DisplayCountry_CurrencyCode: "Syria (SYP)", DisplayCurrencySymbol: "£", SymbolPosition: 0, Country: "Syria", CurrencySymbol: "£" },
  { DisplayCountry: "Taiwan", CurrencyCode: "TWD", DisplayCountry_CurrencyCode: "Taiwan (TWD)", DisplayCurrencySymbol: "NT$", SymbolPosition: 0, Country: "Taiwan", CurrencySymbol: "NT$" },
  { DisplayCountry: "Tajikistan", CurrencyCode: "TJS", DisplayCountry_CurrencyCode: "Tajikistan (TJS)", DisplayCurrencySymbol: "ЅМ", SymbolPosition: 1, Country: "Tajikistan", CurrencySymbol: "ЅМ" },
  { DisplayCountry: "Tanzania", CurrencyCode: "TZS", DisplayCountry_CurrencyCode: "Tanzania (TZS)", DisplayCurrencySymbol: "Sh", SymbolPosition: 0, Country: "Tanzania", CurrencySymbol: "Sh" },
  { DisplayCountry: "Thailand", CurrencyCode: "THB", DisplayCountry_CurrencyCode: "Thailand (THB)", DisplayCurrencySymbol: "฿", SymbolPosition: 0, Country: "Thailand", CurrencySymbol: "฿" },
  { DisplayCountry: "Timor-Leste", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "Timor-Leste (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Timor-Leste", CurrencySymbol: "$" },
  { DisplayCountry: "Togo", CurrencyCode: "XOF", DisplayCountry_CurrencyCode: "Togo (XOF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Togo", CurrencySymbol: "Franc" },
  { DisplayCountry: "Tokelau", CurrencyCode: "NZD", DisplayCountry_CurrencyCode: "Tokelau (NZD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Tokelau", CurrencySymbol: "$" },
  { DisplayCountry: "Tonga", CurrencyCode: "TOP", DisplayCountry_CurrencyCode: "Tonga (TOP)", DisplayCurrencySymbol: "T$", SymbolPosition: 0, Country: "Tonga", CurrencySymbol: "T$" },
  { DisplayCountry: "Trinidad and Tobago", CurrencyCode: "TTD", DisplayCountry_CurrencyCode: "Trinidad and Tobago (TTD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Trinidad and Tobago", CurrencySymbol: "$" },
  { DisplayCountry: "Tunisia", CurrencyCode: "TND", DisplayCountry_CurrencyCode: "Tunisia (TND)", DisplayCurrencySymbol: "د.ت", SymbolPosition: 0, Country: "Tunisia", CurrencySymbol: "د.ت" },
  { DisplayCountry: "Turkey", CurrencyCode: "TRY", DisplayCountry_CurrencyCode: "Turkey (TRY)", DisplayCurrencySymbol: "TL", SymbolPosition: 0, Country: "Turkey", CurrencySymbol: "TL" },
  { DisplayCountry: "Turkmenistan", CurrencyCode: "TMT", DisplayCountry_CurrencyCode: "Turkmenistan (TMT)", DisplayCurrencySymbol: "m", SymbolPosition: 1, Country: "Turkmenistan", CurrencySymbol: "m" },
  { DisplayCountry: "Turks & Caicos Islands", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "Turks & Caicos Islands (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Turks and Caicos Islands", CurrencySymbol: "$" },
  { DisplayCountry: "Tuvalu", CurrencyCode: "AUD", DisplayCountry_CurrencyCode: "Tuvalu (AUD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Tuvalu", CurrencySymbol: "$" },
  { DisplayCountry: "Uganda", CurrencyCode: "UGX", DisplayCountry_CurrencyCode: "Uganda (UGX)", DisplayCurrencySymbol: "Sh", SymbolPosition: 0, Country: "Uganda", CurrencySymbol: "Sh" },
  { DisplayCountry: "Ukraine", CurrencyCode: "UAH", DisplayCountry_CurrencyCode: "Ukraine (UAH)", DisplayCurrencySymbol: "₴", SymbolPosition: 1, Country: "Ukraine", CurrencySymbol: "₴" },
  { DisplayCountry: "United Arab Emirates", CurrencyCode: "AED", DisplayCountry_CurrencyCode: "United Arab Emirates (AED)", DisplayCurrencySymbol: "د.م.", SymbolPosition: 0, Country: "United Arab Emirates", CurrencySymbol: "د.م." },
  { DisplayCountry: "United Kingdom", CurrencyCode: "GBP", DisplayCountry_CurrencyCode: "United Kingdom (GBP)", DisplayCurrencySymbol: "£", SymbolPosition: 0, Country: "United Kingdom", CurrencySymbol: "£" },
  { DisplayCountry: "US Minor Outlying Is.", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "US Minor Outlying Is. (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "United States Minor Outlying Islands", CurrencySymbol: "$" },
  { DisplayCountry: "United States", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "United States (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "United States of America", CurrencySymbol: "$" },
  { DisplayCountry: "Uruguay", CurrencyCode: "UYU", DisplayCountry_CurrencyCode: "Uruguay (UYU)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Uruguay", CurrencySymbol: "$" },
  { DisplayCountry: "Uzbekistan", CurrencyCode: "UZS", DisplayCountry_CurrencyCode: "Uzbekistan (UZS)", DisplayCurrencySymbol: "лв", SymbolPosition: 1, Country: "Uzbekistan", CurrencySymbol: "лв" },
  { DisplayCountry: "Vanuatu", CurrencyCode: "VUV", DisplayCountry_CurrencyCode: "Vanuatu (VUV)", DisplayCurrencySymbol: "Vt", SymbolPosition: 0, Country: "Vanuatu", CurrencySymbol: "Vt" },
  { DisplayCountry: "Venezuela", CurrencyCode: "VEF", DisplayCountry_CurrencyCode: "Venezuela (VEF)", DisplayCurrencySymbol: "Bs.", SymbolPosition: 0, Country: "Venezuela", CurrencySymbol: "Bs." },
  { DisplayCountry: "Vietnam", CurrencyCode: "VND", DisplayCountry_CurrencyCode: "Vietnam (VND)", DisplayCurrencySymbol: "₫", SymbolPosition: 1, Country: "Vietnam", CurrencySymbol: "₫" },
  { DisplayCountry: "British Virgin Islands", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "British Virgin Islands (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "British Virgin Islands", CurrencySymbol: "$" },
  { DisplayCountry: "US Virgin Islands", CurrencyCode: "USD", DisplayCountry_CurrencyCode: "US Virgin Islands (USD)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "US Virgin Islands", CurrencySymbol: "$" },
  { DisplayCountry: "Wallis and Futuna", CurrencyCode: "XPF", DisplayCountry_CurrencyCode: "Wallis and Futuna (XPF)", DisplayCurrencySymbol: "Fr", SymbolPosition: 1, Country: "Wallis and Futuna", CurrencySymbol: "Franc" },
  { DisplayCountry: "Western Sahara", CurrencyCode: "MAD", DisplayCountry_CurrencyCode: "Western Sahara (MAD)", DisplayCurrencySymbol: "د.م.", SymbolPosition: 0, Country: "Western Sahara", CurrencySymbol: "د.م." },
  { DisplayCountry: "Yemen", CurrencyCode: "YER", DisplayCountry_CurrencyCode: "Yemen (YER)", DisplayCurrencySymbol: "﷼", SymbolPosition: 0, Country: "Yemen", CurrencySymbol: "﷼" },
  { DisplayCountry: "Zambia", CurrencyCode: "ZMW", DisplayCountry_CurrencyCode: "Zambia (ZMW)", DisplayCurrencySymbol: "ZK", SymbolPosition: 0, Country: "Zambia", CurrencySymbol: "ZK" },
  { DisplayCountry: "Zimbabwe", CurrencyCode: "ZWL", DisplayCountry_CurrencyCode: "Zimbabwe (ZWL)", DisplayCurrencySymbol: "$", SymbolPosition: 0, Country: "Zimbabwe", CurrencySymbol: "$" },
  { DisplayCountry: "Åland Islands", CurrencyCode: "EUR", DisplayCountry_CurrencyCode: "Åland Islands (EUR)", DisplayCurrencySymbol: "€", SymbolPosition: 1, Country: "Åland Islands", CurrencySymbol: "€" },
];

// Helper function to find currency by code
export function getCurrencyByCode(code: string): CurrencyItem | undefined {
  return CURRENCY_DATA.find(currency => currency.CurrencyCode === code);
}

// Helper function to find currency by symbol
export function getCurrencyBySymbol(symbol: string): CurrencyItem | undefined {
  return CURRENCY_DATA.find(currency => currency.CurrencySymbol === symbol);
}

// Format a number according to currency rules
export function formatCurrency(amount: number, currencyCode: string): string {
  const currency = getCurrencyByCode(currencyCode);
  if (!currency) return `${amount}`;
  
  return currency.SymbolPosition === 0 
    ? `${currency.DisplayCurrencySymbol}${amount.toFixed(2)}`
    : `${amount.toFixed(2)}${currency.DisplayCurrencySymbol}`;
} 